# This doesn't build the binary, but after passing tests
# a build and deploy is triggered by the infrastructure repo

name: Go - Test & Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  test:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run Go Tests
        run: go test -v

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ddbgio/ddbg
          event-type: deploy-dawesome
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  # trigger-deploy:
  #   name: Trigger Deploy with Repository Dispatch
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Repository Dispatch from GitHub CLI
  #       env:
  #         GH_TOKEN: ${{ github.token }}          
  #       run: |
  #         # GitHub CLI api
  #         # https://cli.github.com/manual/gh_api
          
  #         gh api \
  #           --method POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           /repos/ddbgio/ddbg/dispatches \
  #            -f "event_type=deploy-dawesome"
