name: Go - Test & Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Run Go Tests
        run: go test -v
